<?php

namespace Src\Trader\Application\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class TraderResource extends JsonResource
{

    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}
